import random
from locust import HttpUser, task, between

class FileApiUser(HttpUser):
    """
    A Locust user that simulates interactions with the File Storage API.
    """
    
    # Users will wait between 1 and 3 seconds between tasks
    wait_time = between(1, 3)

    @task(1)
    def task_get_root(self):
        """Task to hit the root endpoint."""
        self.client.get("/")

    @task(1)
    def task_get_health(self):
        """Task to hit the health check endpoint."""
        self.client.get("/health")

    @task(1)
    def task_get_metrics(self):
        """Task to hit the metrics endpoint."""
        self.client.get("/metrics")

    @task(3)
    def task_list_files(self):
        """Task to list all files."""
        self.client.get("/files")

    @task(10)
    def task_upload_and_get_file(self):
        """
        A high-weight task that simulates the core user flow:
        1. Upload a new file with unique content.
        2. Immediately retrieve that same file and verify its content.
        """
        
        # 1. Generate unique file data
        file_id = random.randint(10000, 999999)
        filename = f"locust_test_file_{file_id}.txt"
        file_content = f"This is test content for file {filename} generated by Locust."
        file_content_bytes = file_content.encode('utf-8')

        # 2. POST (upload) the file
        files_to_upload = {'file': (filename, file_content_bytes, 'text/plain')}
        
        # We use catch_response=True to manually check for success/failure
        with self.client.post("/files", files=files_to_upload, catch_response=True, name="/files (upload)") as post_response:
            if post_response.status_code != 200:
                post_response.failure(f"Failed to upload file {filename}. Status: {post_response.status_code}")
                return  # Don't try to GET if POST failed

        # 3. GET (download) the file we just uploaded
        with self.client.get(f"/files/{filename}", catch_response=True, name="/files/{filename} (download)") as get_response:
            if get_response.status_code != 200:
                get_response.failure(f"Failed to download file {filename} after upload. Status: {get_response.status_code}")
            elif get_response.content != file_content_bytes:
                get_response.failure(f"Content mismatch for downloaded file {filename}.")
            else:
                get_response.success()